### PR TITLE
fixed issue #217

### PR DESCRIPTION
**Pull request by i128**

### CODE REVIEW

**Comment by bandrel** [comment]
Fixed the failing unit test in 8b881fa.

**Root cause:** the test `test_jobs_start_returns_400_when_job_not_queued` was written against the pre-fix (inverted) guard. With the issue #217 fix in place, a `Ready` job is now correctly allowed to start, so it fell through into `build_hashcat_command` with the test's bogus `task_id=1` and raised `AttributeError: 'NoneType' object has no attribute 'rule_id'`.

**Fix:** updated the test to assert the 400 path that still exists under the new logic — a job that is already `Queued`. Renamed to `test_jobs_start_returns_400_when_job_already_queued`. No production code changed; the fix for #217 is correct.
